import type { RoutePoint, DetectedTurn, MileMarker, Waypoint } from './types';

function escXml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

export function exportGPX(
  routePoints: RoutePoint[],
  detectedTurns: DetectedTurn[],
  mileMarkers: MileMarker[],
  waypoints: Waypoint[]
): string {
  let gpx = `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="Rally Route Builder" xmlns="http://www.topografix.com/GPX/1/1">
  <metadata><name>Rally Route</name><desc>Generated by Rally Route Builder</desc></metadata>
`;

  detectedTurns.forEach((turn, i) => {
    const arrow = turn.direction === 'left' ? 'L' : 'R';
    const label = turn.label || `${turn.sharpness.toUpperCase()} ${arrow} ${turn.angle.toFixed(0)}deg`;
    gpx += `  <wpt lat="${turn.lat}" lon="${turn.lon}"><name>${escXml(label)}</name><desc>Turn ${i + 1}: ${turn.sharpness} ${turn.direction} at ${turn.angle.toFixed(1)} degrees</desc><sym>${turn.sharpness}_${turn.direction}</sym><type>turn</type></wpt>\n`;
  });

  mileMarkers.forEach((mm) => {
    const displayLabel = mm.customLabel || mm.label;
    const sym = mm.icon && mm.icon !== '📏' ? mm.icon : 'mile_marker';
    gpx += `  <wpt lat="${mm.lat}" lon="${mm.lon}"><name>${escXml(displayLabel)}</name><desc>Mile Marker: ${mm.label}</desc><sym>${escXml(sym)}</sym><type>mile_marker</type></wpt>\n`;
  });

  waypoints
    .filter((w) => w.enabled)
    .forEach((wp) => {
      gpx += `  <wpt lat="${wp.lat}" lon="${wp.lon}"><name>${escXml(wp.name)}</name><desc>${escXml(wp.desc || '')}</desc><sym>${wp.icon}</sym><type>waypoint</type></wpt>\n`;
    });

  gpx += `  <trk><name>Route</name><trkseg>\n`;
  routePoints.forEach((p) => {
    gpx += `    <trkpt lat="${p.lat}" lon="${p.lon}">${p.ele !== null && p.ele !== undefined ? '<ele>' + p.ele + '</ele>' : ''}</trkpt>\n`;
  });
  gpx += `  </trkseg></trk>\n</gpx>`;

  return gpx;
}

export function exportKML(
  routePoints: RoutePoint[],
  detectedTurns: DetectedTurn[],
  mileMarkers: MileMarker[],
  waypoints: Waypoint[]
): string {
  const kmlColors: Record<string, string> = {
    flat: 'ffc4cd4e',
    slight: 'ff23a6f5',
    moderate: 'ff1a75e8',
    sharp: 'ff6045e9',
    hairpin: 'ffb6599b',
  };

  let kml = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
<Document>
  <name>Rally Route</name><description>Generated by Rally Route Builder</description>
  <Style id="route"><LineStyle><color>aaffffff</color><width>3</width></LineStyle></Style>
  <Style id="mile_marker"><IconStyle><color>ffff9900</color><scale>0.8</scale><Icon><href>https://maps.google.com/mapfiles/kml/paddle/blu-blank.png</href></Icon></IconStyle></Style>
`;

  Object.entries(kmlColors).forEach(([name, color]) => {
    ['left', 'right'].forEach((dir) => {
      kml += `  <Style id="${name}_${dir}"><IconStyle><color>${color}</color><scale>1.0</scale><Icon><href>https://maps.google.com/mapfiles/kml/shapes/arrow.png</href></Icon></IconStyle><LabelStyle><scale>0.8</scale></LabelStyle></Style>\n`;
    });
  });

  kml += `  <Folder><name>Turns</name>\n`;
  detectedTurns.forEach((turn, i) => {
    const arrow = turn.direction === 'left' ? 'L' : 'R';
    const label = turn.label || `${turn.sharpness.toUpperCase()} ${arrow} ${turn.angle.toFixed(0)}deg`;
    kml += `    <Placemark><name>${escXml(label)}</name><description>Turn ${i + 1}: ${turn.sharpness} ${turn.direction}</description><styleUrl>#${turn.sharpness}_${turn.direction}</styleUrl><Point><coordinates>${turn.lon},${turn.lat},0</coordinates></Point></Placemark>\n`;
  });

  kml += `  </Folder>\n  <Folder><name>Mile Markers</name>\n`;
  mileMarkers.forEach((mm) => {
    const displayLabel = mm.customLabel || mm.label;
    const iconInfo = mm.icon && mm.icon !== '📏' ? mm.icon + ' ' : '';
    kml += `    <Placemark><name>${escXml(iconInfo + displayLabel)}</name><description>Distance: ${mm.label}${mm.icon && mm.icon !== '📏' ? ', icon: ' + mm.icon : ''}</description><styleUrl>#mile_marker</styleUrl><Point><coordinates>${mm.lon},${mm.lat},0</coordinates></Point></Placemark>\n`;
  });
  kml += `  </Folder>\n`;

  const enabledWps = waypoints.filter((w) => w.enabled);
  if (enabledWps.length) {
    kml += `  <Folder><name>Waypoints</name>\n`;
    enabledWps.forEach((wp) => {
      kml += `    <Placemark><name>${escXml(wp.icon + ' ' + wp.name)}</name><description>${escXml(wp.desc || '')}</description><Point><coordinates>${wp.lon},${wp.lat},${wp.ele || 0}</coordinates></Point></Placemark>\n`;
    });
    kml += `  </Folder>\n`;
  }

  const coordStr = routePoints.map((p) => `${p.lon},${p.lat},${p.ele || 0}`).join('\n      ');
  kml += `  <Placemark><name>Route</name><styleUrl>#route</styleUrl><LineString><tessellate>1</tessellate><coordinates>\n      ${coordStr}\n    </coordinates></LineString></Placemark>\n</Document></kml>`;

  return kml;
}

export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
