import type { RoutePoint, DetectedTurn, MileMarker, Waypoint } from './types';
import { TURN_GRADES, turnCode } from './types';
import { garminMileSymbol, garminTurnSymbol, garminWaypointSymbol, turnComment } from './garmin';

const GPX_WPT_EXTENSION = `<extensions><gpxx:WaypointExtension><gpxx:DisplayMode>SymbolAndName</gpxx:DisplayMode></gpxx:WaypointExtension></extensions>`;

function escXml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

export function exportGPX(
  routePoints: RoutePoint[],
  detectedTurns: DetectedTurn[],
  mileMarkers: MileMarker[],
  waypoints: Waypoint[]
): string {
  let gpx = `<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1" creator="Rally Route Builder"
  xmlns="http://www.topografix.com/GPX/1/1"
  xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd http://www.garmin.com/xmlschemas/GpxExtensions/v3 http://www8.garmin.com/xmlschemas/GpxExtensionsv3.xsd">
  <metadata><name>Rally Route</name><desc>Generated by Rally Route Builder</desc></metadata>
`;

  detectedTurns.forEach((turn, i) => {
    const code = turnCode(turn.direction, turn.grade);
    const label = turn.label || `${code} ${turn.angle.toFixed(0)}deg`;
    const sym = garminTurnSymbol(turn.direction, turn.grade);
    gpx += `  <wpt lat="${turn.lat}" lon="${turn.lon}"><name>${escXml(label)}</name><cmt>${turnComment(turn)}</cmt><desc>Turn ${i + 1}: ${code} ${turn.direction} at ${turn.angle.toFixed(1)} degrees</desc><sym>${escXml(sym)}</sym><type>turn</type>${GPX_WPT_EXTENSION}</wpt>\n`;
  });

  mileMarkers.forEach((mm) => {
    const displayLabel = mm.customLabel || mm.label;
    const appIcon = mm.icon && mm.icon !== '📏' ? mm.icon : '';
    const sym = appIcon ? garminWaypointSymbol(appIcon) : garminMileSymbol();
    const cmt = appIcon ? `<cmt>${escXml(appIcon)}</cmt>` : '';
    gpx += `  <wpt lat="${mm.lat}" lon="${mm.lon}"><name>${escXml(displayLabel)}</name>${cmt}<desc>Mile Marker: ${mm.label}</desc><sym>${escXml(sym)}</sym><type>mile_marker</type>${GPX_WPT_EXTENSION}</wpt>\n`;
  });

  waypoints
    .filter((w) => w.enabled)
    .forEach((wp) => {
      const cmt = wp.icon ? `<cmt>${escXml(wp.icon)}</cmt>` : '';
      gpx += `  <wpt lat="${wp.lat}" lon="${wp.lon}"><name>${escXml(wp.name)}</name>${cmt}<desc>${escXml(wp.desc || '')}</desc><sym>${escXml(garminWaypointSymbol(wp.icon))}</sym><type>waypoint</type>${GPX_WPT_EXTENSION}</wpt>\n`;
    });

  gpx += `  <trk><name>Route</name><trkseg>\n`;
  routePoints.forEach((p) => {
    gpx += `    <trkpt lat="${p.lat}" lon="${p.lon}">${p.ele !== null && p.ele !== undefined ? '<ele>' + p.ele + '</ele>' : ''}</trkpt>\n`;
  });
  gpx += `  </trkseg></trk>\n</gpx>`;

  return gpx;
}

export function exportKML(
  routePoints: RoutePoint[],
  detectedTurns: DetectedTurn[],
  mileMarkers: MileMarker[],
  waypoints: Waypoint[]
): string {
  const kmlColors: Record<string, string> = {
    1: 'ffb6599b',
    2: 'ff6045e9',
    3: 'ff1a75e8',
    4: 'ff23a6f5',
    5: 'ff4ca8c9',
    6: 'ffc4cd4e',
  };

  let kml = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
<Document>
  <name>Rally Route</name><description>Generated by Rally Route Builder</description>
  <Style id="route"><LineStyle><color>aaffffff</color><width>3</width></LineStyle></Style>
  <Style id="mile_marker"><IconStyle><color>ffff9900</color><scale>0.8</scale><Icon><href>https://maps.google.com/mapfiles/kml/paddle/blu-blank.png</href></Icon></IconStyle></Style>
`;

  TURN_GRADES.forEach((grade) => {
    const color = kmlColors[String(grade)];
    ['left', 'right'].forEach((dir) => {
      kml += `  <Style id="${grade}_${dir}"><IconStyle><color>${color}</color><scale>1.0</scale><Icon><href>https://maps.google.com/mapfiles/kml/shapes/arrow.png</href></Icon></IconStyle><LabelStyle><scale>0.8</scale></LabelStyle></Style>\n`;
    });
  });

  kml += `  <Folder><name>Turns</name>\n`;
  detectedTurns.forEach((turn, i) => {
    const code = turnCode(turn.direction, turn.grade);
    const label = turn.label || `${code} ${turn.angle.toFixed(0)}deg`;
    kml += `    <Placemark><name>${escXml(label)}</name><description>Turn ${i + 1}: ${code} ${turn.direction}</description><styleUrl>#${turn.grade}_${turn.direction}</styleUrl><Point><coordinates>${turn.lon},${turn.lat},0</coordinates></Point></Placemark>\n`;
  });

  kml += `  </Folder>\n  <Folder><name>Mile Markers</name>\n`;
  mileMarkers.forEach((mm) => {
    const displayLabel = mm.customLabel || mm.label;
    const iconInfo = mm.icon && mm.icon !== '📏' ? mm.icon + ' ' : '';
    kml += `    <Placemark><name>${escXml(iconInfo + displayLabel)}</name><description>Distance: ${mm.label}${mm.icon && mm.icon !== '📏' ? ', icon: ' + mm.icon : ''}</description><styleUrl>#mile_marker</styleUrl><Point><coordinates>${mm.lon},${mm.lat},0</coordinates></Point></Placemark>\n`;
  });
  kml += `  </Folder>\n`;

  const enabledWps = waypoints.filter((w) => w.enabled);
  if (enabledWps.length) {
    kml += `  <Folder><name>Waypoints</name>\n`;
    enabledWps.forEach((wp) => {
      kml += `    <Placemark><name>${escXml(wp.icon + ' ' + wp.name)}</name><description>${escXml(wp.desc || '')}</description><Point><coordinates>${wp.lon},${wp.lat},${wp.ele || 0}</coordinates></Point></Placemark>\n`;
    });
    kml += `  </Folder>\n`;
  }

  const coordStr = routePoints.map((p) => `${p.lon},${p.lat},${p.ele || 0}`).join('\n      ');
  kml += `  <Placemark><name>Route</name><styleUrl>#route</styleUrl><LineString><tessellate>1</tessellate><coordinates>\n      ${coordStr}\n    </coordinates></LineString></Placemark>\n</Document></kml>`;

  return kml;
}

export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
